name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build the game
        run: |
          make
          ./tzozen_test
        env:
          CC: gcc
